server:
  port: 8081
spring:
  application:
    name: item-service
  rabbitmq:
    host: 192.168.0.135
    username: mceil
    password: mceil
    virtual-host: /mceil
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: mc.item.exchange
    publisher-confirms: true
  datasource:
    url: jdbc:mysql://192.168.0.135:3306/mceil?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance: #防止网络不稳定导致ip错乱，把ip写死
    prefer-ip-address: true
    #ip-address: ${spring.cloud.client.ipAddress}:${server.port}
    #ip-address: 127.0.0.1${spring.cloud.client.ipAddress}:${server.port}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl