server:
  port: 8086
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://192.168.0.135:3306/mceil?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.0.135
    username: mceil
    password: mceil
    virtual-host: /mceil
  redis:
    host: 192.168.0.135
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  type-aliases-package: com.mceil.user.pojo