server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.0.135
  rabbitmq:
    host: 192.168.0.135
    username: mceil
    password: mceil
    virtual-host: /mceil
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
#    ip-address: 127.0.0.1
#    instance-id: ${spring.application.name}.${server.port}
mc:
  jwt:
    pubKeyPath: D:\\mall\\keykey\\rsa.pub # 公钥地址
    cookieName: MC_TOKEN